version: "3"

services:
  server:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./shared/public_html:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./shared/dbdata:/var/lib/mysql
